# Generated by Django 5.0.7 on 2024-07-24 06:17

import django.db.models.deletion
from django.db import migrations, models


from django.db import migrations, models


from django.db import migrations, models


def set_default_student(apps, schema_editor):
    Enrollment = apps.get_model("school", "Enrollment")
    Student = apps.get_model("school", "Student")
    default_student = (
        Student.objects.first()
    )  # Or create a default student if none exist
    Enrollment.objects.filter(student__isnull=True).update(student=default_student)


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_enrollment_student"),
    ]

    operations = [
        migrations.RunPython(set_default_student),
    ]
